//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackjack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public string Genre { get; set; }
        public string URL { get; set; }
        public Nullable<bool> IsFinal { get; set; }
        public string ChoiceID { get; set; }
        public int ExcursionID { get; set; }
        public string ChoiceName { get; set; }
        public int Votes { get; set; }
        public string imageURL { get; set; }
    
        public virtual Excursion Excursion { get; set; }
    }
}
